export default {
    products:[
        {
            _id: 1,
            name: ' Slim Shirt1',
            category:'Shirts',
            image:'/images/d1.jpeg',
            price: 60,
            brand: ' Nike ',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 2,
            name: ' Slim Shirt2',
            category:'Shirts',
            image:'/images/d1.jpeg',
            price: 60,
            brand: ' Nike ',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        }, 
        {
            _id: 3,
            name: ' Slim Shirt3',
            category:'Shirts',
            image:'/images/d1.jpeg',
            price: 60,
            brand: ' Nike ',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 4,
            name: ' Slim Shirt4',
            category:'Shirts',
            image:'/images/d1.jpeg',
            price: 60,
            brand: ' Nike ',
            rating: 4.5,
            numReviews: 10,
            countInStock: 0,
        },
        {
            _id: 5,
            name: ' Slim Shirt5',
            category:'Shirts',
            image:'/images/d1.jpeg',
            price: 60,
            brand: ' Nike ',
            rating: 4.5,
            numReviews: 10,
            countInStock: 8,
        },
        {
            _id: 6, 
            name: ' Slim Shirt6',
            category:'Shirts',
            image:'/images/d1.jpeg',
            price: 60,
            brand: ' Nike ',
            rating: 4.5,
            numReviews: 10,
            countInStock: 9,
        }
        ,{
            _id: 7,
            name: ' Slim Shirt7',
            category:'Shirts',
            image:'/images/d1.jpeg',
            price: 60,
            brand: ' Nike ',
            rating: 4.5,
            numReviews: 10,
            countInStock: 10,
        }
    ]
}